class RandomData {
  words = [
    'Lorem',
    'ipsum',
    'dolor',
    'sit',
    'amet',
    'consectetur',
    'adipiscing',
    'elit',
    'Mauris',
    'rhoncus',
    'dolor',
    'non',
    'neque',
    'molestie',
    'rutrum',
    'Aliquam',
    'erat',
    'volutpat',
    'Donec',
    'porta',
    'odio',
    'est',
    'et',
    'venenatis',
    'risus',
    'fringilla',
    'at',
    'Phasellus',
    'molestie',
    'facilisis',
    'vehicula',
    'Maecenas',
    'at',
    'ultrices',
    'nunc',
    'pretium',
    'sem',
    'Vestibulum',
    'tincidunt',
    'risus',
    'in',
    'volutpat',
    'aliquam',
    'diam',
    'orci',
    'consectetur',
    'dolor',
    'eu',
    'volutpat',
    'purus',
    'felis',
    'eu',
    'mauris',
    'Praesent',
    'eros',
    'quis',
    'libero',
    'imperdiet',
    'rutrum',
    'quis',
    'non',
    'turpis',
    'Morbi',
    'at',
    'tincidunt',
    'lacus',
    'sed',
    'placerat',
    'tortor',
    'Cras',
    'ac',
    'congue',
    'elit',
    'Vestibulum',
    'consectetur',
    'pellentesque',
    'eros',
    'et',
    'volutpat',
    'purus',
    'lacinia',
    'ac',
    'Quisque',
    'mollis',
    'dui',
    'vel',
    'lectus',
    'cursus',
    'lobortis',
    'Suspendisse',
    'ultricies',
    'ligula',
    'ut',
    'ullamcorper',
    'commodo',
    'Sed',
    'id',
    'interdum',
    'ligula',
    'Pellentesque',
    'pellentesque',
    'sem',
    'ut',
    'ex',
    'laoreet',
    'viverra',
    'Phasellus',
    'gravida',
    'finibus',
    'nisl',
    'et',
    'commodo',
    'Aenean',
    'maximus',
    'faucibus',
    'mollis',
    'Phasellus',
    'feugiat',
    'lacus',
    'non',
    'erat',
    'tempor',
    'condimentum',
    'Etiam',
    'sed',
    'felis',
    'ac',
    'nisi',
    'suscipit',
    'feugiat',
    'quis',
    'eget',
    'felis',
    'Lorem',
    'ipsum',
    'dolor',
    'sit',
    'amet',
    'consectetur',
    'adipiscing',
    'elit'
  ];

  rndNum(min: number, max: number) {
    return Math.ceil(Math.random() * (max - min) + min);
  }

  getRandomName() {
    const len = this.words.length;
    const num = this.rndNum(0, len - 1);
    return this.words[num];
  }

  getRandomData() {
    let a = [];
    a.push(this.getRandomName());
    const max = 20;
    for (let i = 0; i < max; i++) {
      a.push(this.rndNum(-500, 500));
    }
    return a;
  }
}

export default RandomData;
